---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - port: 8000
  type: NodePort
